=== ExecutionLLC/gen-bs/docs/as-ws-schema/base_json/file_metadata.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "description of the file structure",
  "type": "object",
  "properties": {
    "reference": {
      "type": "string",
      "description": "string id of assemblies reference"
    },
    "genotypes": {
      "type": "array",
      "description": "Optional. Contains names of the genotypes in the file.",
      "items": {
        "type": "string"
      }
    },
    "columns": {
      "type": "array",
      "description": "list of the columns metadata common for all genotypes found in the sample",
      "items": {
        "$ref": "./column_metadata.json"
      }
    },
    "genotype_columns": {
      "type": "array",
      "description": "Optional, absent in case the uploaded VCF file has no genotype columns.",
      "items": {
        "$ref": "./column_metadata.json"
      }
    }
  }
}

=== ExecutionLLC/gen-bs/database/migrations/20161005115436_default-samples-update/metadata_Patient's VCF File.json
{
  "genotype_columns": [
    "GT_GT",
    "GT_GT_Zygosity",
    "GT_GT_Genotype",
    "GT_GQ",
    "GT_SDP",
    "GT_DP",
    "GT_RD",
    "GT_AD",
    "GT_FREQ",
    "GT_PVAL",
    "GT_RBQ",
    "GT_ABQ",
    "GT_RDF",
    "GT_RDR",
    "GT_ADF",
    "GT_ADR"
  ],
  "columns": [
    {
      "name": "INFO_NC",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Number of samples not called"
    },
    {
      "name": "VEP_STRAND",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_PICK",
      "is_mandatory": false,
      "num": 1,
      "type": "boolean",
      "desc": ""
    },
    {
      "name": "VEP_ExonNumber",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": "starting with 1"
    },
    {
      "name": "INFO_ADP",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Average per-sample depth of bases with Phred score >= 0"
    },
    {
      "name": "VEP_HGMD",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_HGVSp_transcript",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "for use in HGVSp notation (left part before period glyph)"
    },
    {
      "name": "VEP_Feature",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_NumberOfExons",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_SYMBOL",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "Gene ID in database from \"Gene DB\" column"
    },
    {
      "name": "VEP_MOTIF_NAME",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_HGVSc_nucleotide_changes",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "in HGVSc transcript coordinates"
    },
    {
      "name": "VEP_Zygosity",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "Heterozygous, Homozygous, Hemizygous, Unknown. Indels considered equal for zygosity"
    },
    {
      "name": "VEP_cDNA_position_0",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Start position."
    },
    {
      "name": "VEP_SYMBOL_SOURCE",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "database for \"Gene ID\" column"
    },
    {
      "name": "VEP_TREMBL",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "best match"
    },
    {
      "name": "VEP_DOMAINS",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_CLIN_SIG",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_Gene",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "REF",
      "is_mandatory": true,
      "num": 0,
      "type": "string",
      "desc": "The value in the POS field refers to the position of the first base in the String."
    },
    {
      "name": "VEP_MOTIF_SCORE_CHANGE",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_PHENO",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "Indicates if existing variant is associated with a phenotype, disease or trait"
    },
    {
      "name": "VEP_CANONICAL",
      "is_mandatory": false,
      "num": 0,
      "type": "float",
      "desc": ""
    },
    {
      "name": "INFO_HOM",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Number of samples called homozygous-variant"
    },
    {
      "name": "VEP_TSL",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_HIGH_INF_POS",
      "is_mandatory": false,
      "num": 1,
      "type": "boolean",
      "desc": ""
    },
    {
      "name": "VEP_NumberOfIntrons",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_HGVSp_nucleotide_changes",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "in HGVSp transcript coordinates"
    },
    {
      "name": "VEP_cDNA_position_1",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Stop position."
    },
    {
      "name": "VEP_IMPACT",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "high impact, changed protein effectiveness , no change, no evidence or difficult to predict"
    },
    {
      "name": "VEP_HGVS_OFFSET",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": "HGVS was calculated after ambiguous repeat shift. Column shows shift size"
    },
    {
      "name": "INFO_HET",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Number of samples called heterozygous-variant"
    },
    {
      "name": "VEP_DISTANCE",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_CCDS",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_BIOTYPE",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "Gene type in Havana DB. Protein coding: IGC gene, IGD gene, IG gene, IGJ gene, IGLV gene, IGM gene, IGV gene, IGZ gene, nonsense mediated decay, nontranslating CDS, non stop decay, polymorphic pseudogene, TRC gene, TRD gene, TRJ gene. Pseudogene: disrupted domain, IGC pseudogene, IGJ pseudogene, IG pseudogene, IGV pseudogene, processed pseudogene, transcribed processed pseudogene, transcribed unitary pseudogene, transcribed unprocessed pseudogene, translated processed pseudogene, TRJ pseudogene, unprocessed pseudogene. Long noncoding: 3prime overlapping ncrna, ambiguous orf, antisense, antisense RNA, lincRNA, ncrna host, processed transcript, sense intronic, sense overlapping. Short noncoding: miRNA, miRNA_pseudogene, miscRNA, miscRNA pseudogene, Mt rRNA, Mt tRNA, rRNA, scRNA, snlRNA, snoRNA, snRNA, tRNA, tRNA_pseudogene"
    },
    {
      "name": "VEP_IntronNumber",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_GENE_PHENO",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "QUAL",
      "is_mandatory": true,
      "num": 1,
      "type": "float",
      "desc": "Quality."
    },
    {
      "name": "VEP_HGVSc_transcript",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "for use in HGVSc notation (left part before period glyph)"
    },
    {
      "name": "ALT",
      "is_mandatory": true,
      "num": 0,
      "type": "string",
      "desc": "Comma separated list of alternate non-reference alleles called on at least one of the samples."
    },
    {
      "name": "VEP_ALLELE_NUM",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_HGNC_ID",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "INFO_WT",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Number of samples called reference (wild-type)"
    },
    {
      "name": "VEP_PolyPhen",
      "is_mandatory": false,
      "num": 0,
      "type": "float",
      "desc": "PolyPhen-2 v2.2.2. Probability(variation is deleterious). Common threshold is 0.95"
    },
    {
      "name": "ID",
      "is_mandatory": true,
      "num": 0,
      "type": "string",
      "desc": "Semi-colon separated list of unique identifiers where available."
    },
    {
      "name": "VEP_Amino_acids",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_VARIANT_CLASS",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "SNV (single nucleotide variant), insertion, deletion, indel, MNP (multiple nucleotide polymorphism), MNV (multiple nucleotide variant), duplication, sequence alteration, inversion, microsatellite, monomeric repeat, CNL (copy number loss), CNG (copy number gain), CNV (copy number variation), MEI (mobile element insertion), NSI (novel sequence insertion), complex, tandem duplication, translocation, no variation"
    },
    {
      "name": "VEP_CDS_position_1",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Stop position."
    },
    {
      "name": "VEP_CDS_position_0",
      "is_mandatory": false,
      "num": 1,
      "type": "integer",
      "desc": "Start position."
    },
    {
      "name": "VEP_Existing_variation",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_Allele",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_SWISSPROT",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": "best match"
    },
    {
      "name": "CHROM",
      "is_mandatory": true,
      "num": 1,
      "type": "integer",
      "desc": "Chromosome identifier."
    },
    {
      "name": "VEP_CELL_TYPE",
      "is_mandatory": false,
      "num": 0,
      "type": "string",
      "desc": ""
    },
    {
      "name": "VEP_MOTIF_POS",
      "is_mandatory": false,
      "num": 0,
      "type": "integer",
      "desc": ""
    },
    {
      "name": "VEP_Consequence",
      "is_mandatory": false,
      "num": 0,
