=== ExecutionLLC/gen-bs/docs/ws-internal/field-metadata-template.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "One field metadata template",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "UUID, the unique identifier for the field metadata"
    },
    "name": {
      "type": "string",
      "description": "Field metadata name"
    },
    "label": {
      "type": "string",
      "description": "Field metadata user-friendly name"
    },
    "source_name": {
      "type": "string",
      "description": "Field metadata source name, 'sample' for sample field metadata"
    },
    "is_editable": {
      "type": "boolean",
      "description": "Field metadata editable sign"
    },
    "is_mandatory": {
      "type": "boolean",
      "description": "Field metadata mandatory"
    },
    "value_type": {
      "type": "string",
      "enum": [
        "string",
        "integer",
        "boolean",
        "float"
      ],
      "description": "Field metadata value type"
    },
    "description": {
      "description": "Localized field metadata description for UI",
      "type": "string"
    },
    "dimension": {
      "type": "integer",
      "description": "Reference genom vcf coordinate system version"
    }
  },
  "required": [
    "id",
    "name",
    "label",
    "source_name",
    "is_editable",
    "is_mandatory",
    "value_type",
    "description",
    "dimension"
  ]
}

=== ExecutionLLC/gen-bs/defaults/templates/metadata/required-metadata.json
[
  {
    "id": "00000000-0000-0000-0000-00000000001",
    "name": "CHROM",
    "label": "CHROM",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "integer",
    "description": "Chromosome identifier",
    "dimension": 1
  },
  {
    "id": "00000000-0000-0000-0000-00000000002",
    "name": "POS",
    "label": "POS",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "integer",
    "description": "The reference position",
    "dimension": 1
  },
  {
    "id": "00000000-0000-0000-0000-00000000003",
    "name": "ID",
    "label": "ID",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "string",
    "description": "Semi-colon separated list of unique identifiers where available",
    "dimension": 0
  },
  {
    "id": "00000000-0000-0000-0000-00000000004",
    "name": "REF",
    "label": "REF",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "string",
    "description": "The value in the POS field refers to the position of the first base in the String",
    "dimension": 0
  },
  {
    "id": "00000000-0000-0000-0000-00000000005",
    "name": "ALT",
    "label": "ALT",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "string",
    "description": "Comma separated list of alternate non-reference alleles called on at least one of the samples",
    "dimension": 0
  },
  {
    "id": "00000000-0000-0000-0000-00000000006",
    "name": "QUAL",
    "label": "QUAL",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "float",
    "description": "Quality",
    "dimension": 1
  },
  {
    "id": "00000000-0000-0000-0000-00000000007",
    "name": "FILTER",
    "label": "FILTER",
    "source_name": "sample",
    "is_editable": false,
    "is_mandatory": true,
    "value_type": "string",
    "description": "Filter status",
    "dimension": 0
  }
]
