=== ExecutionLLC/gen-bs/docs/ws-internal/keyword-template.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "One keyword template",
  "type": "object",
  "properties": {
    "field": {
      "$ref": "./field-template.json#"
    },
    "name": {
      "type": "string",
      "description": "Keyword unique name defined from user"
    },
    "value": {
      "type": "string",
      "description": "Keyword value"
    },
    "synonyms": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "description": "Keyword synonyms list",
      "items": {
        "$ref": "./synonym-template.json#"
      }
    }
  },
  "required": [
    "field",
    "name",
    "value",
    "synonyms"
  ]
}

=== ExecutionLLC/gen-bs/defaults/templates/keyword-templates.json
[
  {
    "field": {
      "source_name": "sample",
      "name": "ALT",
      "value_type": "string"
    },
    "name": "ALT A",
    "value": "A",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "Synonym of ALT A"
      }
    ]
  },
  {
    "field": {
      "source_name": "sample",
      "name": "ALT",
      "value_type": "string"
    },
    "name": "ALT C",
    "value": "C",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "Synonym of ALT C"
      }
    ]
  }
]
