=== ExecutionLLC/gen-bs/docs/ws-internal/user.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "User",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "UUID, the unique identifier for user"
    },
    "name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "speciality": {
      "type": "string"
    },
    "language": {
      "type": "string",
      "maxLength": 2
    },
    "number_paid_samples": {
      "type": "integer"
    },
    "login": {
      "type": "string"
    },
    "password": {
      "type": "string"
    }
  }
}

=== ExecutionLLC/gen-bs/defaults/users/default-users.json
[
  {
    "id": "00000000-0000-0000-0000-000000000000",
    "name": "Demo",
    "last_name": "Demo",
    "email": "demo@demo.com",
    "speciality": "doctor",
    "language": "en",
    "number_paid_samples": 0
  },
  {
    "id": "373116ac-a0e8-4afd-aa48-3c0bf7614951",
    "name": "Valarie",
    "last_name": "Vaughn",
    "email": "valarievaughn@electonic.com",
    "speciality": "doctor",
    "language": "en",
    "number_paid_samples": 10,
    "login": "valarie",
    "password": "password"
  },
  {
    "id": "421214ac-a1e9-5afd-aa48-3c0bf7614123",
    "name": "Maria",
    "last_name": "Kuri",
    "email": "mariakuri@electonic.com",
    "speciality": "assistant",
    "language": "en",
    "number_paid_samples": 11,
    "login": "maria",
    "password": "password"
  },
  {
    "id": "9ca148e5-548a-4a78-8e92-ca7563f78775",
    "name": "Vasily",
    "last_name": "Loginov",
    "email": "loginov.vasily@gmail.com",
    "speciality": "Developer",
    "language": "en",
    "number_paid_samples": 11,
    "login": "vasily",
    "password": "zxcasdqwe"
  },
  {
    "id": "5f639c9a-b080-4cf6-a185-28db95d1b489",
    "name": "Elena",
    "last_name": "Baranova",
    "email": "e.elfairy@gmail.com",
    "speciality": "Developer",
    "language": "en",
    "number_paid_samples": 11,
    "login": "elena",
    "password": "zxcasdqwe"
  },
  {
    "id": "3ba433bd-72c8-454e-9822-174a03aa0ba3",
    "name": "Igor",
    "last_name": "Kalgin",
    "email": "ivkalgin@gmail.com",
    "speciality": "Developer",
    "language": "en",
    "number_paid_samples": 11,
    "login": "igor",
    "password": "zxcasdqwe"
  },
  {
    "id": "9e35c2df-489f-44fa-a0da-3fe3cce41906",
    "name": "Maxim",
    "last_name": "Borshev",
    "email": "mtunetworks@gmail.com",
    "speciality": "Developer",
    "language": "en",
    "number_paid_samples": 11,
    "login": "maxim",
    "password": "zxcasdqwe"
  },
  {
    "id": "1036c2df-489f-45fa-a0da-3ae3cce41955",
    "name": "Sergey",
    "last_name": "Vatagin",
    "email": "s.vatagin@gmail.com",
    "speciality": "Developer",
    "language": "en",
    "number_paid_samples": 11,
    "login": "vatic",
    "password": "zxcasdqwe"
  }
]
