=== ExecutionLLC/gen-bs/docs/ws-internal/view-template.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "One view",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "description": "Localized filter description for UI",
      "type": "string"
    },
    "type": {
      "type": "string",
      "description": "Standard - available for demo-user, advanced - only for registered.",
      "enum": [
        "standard",
        "advanced",
        "user"
      ]
    },
    "items": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "./view_list_item.json#"
      }
    }
  },
  "required": [
    "name",
    "type",
    "items"
  ]
}

=== ExecutionLLC/gen-bs/defaults/templates/view-templates.json
[
  {
    "name": "Test Default View",
    "description": "This is default view with two columns and no keywords",
    "type": "standard",
    "items": [
      {
        "field": {
          "source_name": "sample",
          "name": "CHROM",
          "value_type": "integer"
        },
        "keywords": [
          "CHROM 1",
          "CHROM 2"
        ],
        "order": 1,
        "sort_order": 1,
        "sort_direction": "asc"
      },
      {
        "field": {
          "source_name": "sample",
          "name": "POS",
          "value_type": "integer"
        },
        "keywords": [
          "Position"
        ],
        "order": 2,
        "sort_order": 2,
        "sort_direction": "desc"
      },
      {
        "field": {
          "source_name": "sample",
          "name": "FILTER",
          "value_type": "string"
        },
        "keywords": [],
        "order": 6
      },
      {
        "field": {
          "source_name": "common_no_known_medical_impact_20151201",
          "name": "INFO_RSPOS",
          "value_type": "integer"
        },
        "order": 3
      },
      {
        "field": {
          "source_name": "common_no_known_medical_impact_20151201",
          "name": "INFO_VP",
          "value_type": "string"
        },
        "order": 4
      },
      {
        "field": {
          "source_name": "sample",
          "name": "ALT",
          "value_type": "string"
        },
        "keywords": [],
        "order": 5
      }
    ]
  },
  {
    "name": "Another Default View",
    "description": "This is default view with two columns and no keywords",
    "type": "advanced",
    "items": [
      {
        "field": {
          "source_name": "sample",
          "name": "CHROM",
          "value_type": "integer"
        },
        "keywords": [
          "CHROM 1"
        ],
        "order": 1,
        "sort_order": 1,
        "sort_direction": "asc"
      },
      {
        "field": {
          "source_name": "sample",
          "name": "POS",
          "value_type": "integer"
        },
        "keywords": [],
        "order": 2,
        "sort_order": 2,
        "sort_direction": "desc"
      },
      {
        "field": {
          "source_name": "sample",
          "name": "FILTER",
          "value_type": "string"
        },
        "keywords": [],
        "order": 3
      },
      {
        "field": {
          "source_name": "sample",
          "name": "ALT",
          "value_type": "string"
        },
        "keywords": [],
        "order": 4
      }
    ]
  }
]
