=== ExecutionLLC/gen-bs/docs/json-schema-project/json/base_json/keyword.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Keyword Title",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"description": "UUID, the unique identifier for a keyword"
		},
		"field_id": {
			"type": "string",
			"description": "UUID of the corresponding field."
		},
		"name": {
			"type": "string"
		},
		"value": {
			"type": "string",
			"maxLength": 50
		},
		"synonyms": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"keyword_id": {
						"type": "string",
						"description": "UUID of the keyword for this synonym"
					},
					"value": {
						"type": "string",
						"maxLength": 50
					}
				}
			}
		}
	},
	"required": [
		"id"
	]
}

=== ExecutionLLC/gen-bs/database/defaults/keywords/default-keywords.json
[
  {
    "id": "ef7ceb37-de43-4a82-9f45-19bb5d091b61",
    "field_id": "00000000-0000-0000-0000-000000000005",
    "name": "ALT A",
    "value": "A",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "Synonym of ALT A"
      }
    ]
  },
  {
    "id": "44c6115a-84a1-48a5-9f9c-96d2c1dbc312",
    "field_id": "00000000-0000-0000-0000-000000000005",
    "name": "ALT C",
    "value": "C",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "Synonym of ALT C"
      }
    ]
  }
]

=== ExecutionLLC/gen-bs/defaults/keywords/default-keywords.json
[
  {
    "id": "7f9cddc1-b3c4-47c1-9c61-24c7c9d1c8ae",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM ipsum",
    "value": "ipsum",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "et"
      },
      {
        "langu_id": "en",
        "value": "pariatur"
      },
      {
        "langu_id": "en",
        "value": "magna"
      }
    ]
  },
  {
    "id": "868cd759-e9f2-4a49-b417-e5d76d070cd1",
    "field_id": "00000000-0000-0000-0000-000000000002",
    "name": "POS consequat",
    "value": "consequat",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "mollit"
      },
      {
        "langu_id": "en",
        "value": "occaecat"
      },
      {
        "langu_id": "en",
        "value": "magna"
      }
    ]
  },
  {
    "id": "7bf86602-938c-4b68-a5db-4df64f5ccc29",
    "field_id": "00000000-0000-0000-0000-000000000003",
    "name": "ID est",
    "value": "est",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "irure"
      },
      {
        "langu_id": "en",
        "value": "officia"
      },
      {
        "langu_id": "en",
        "value": "do"
      }
    ]
  },
  {
    "id": "3f744724-8b6d-4aaa-8afa-225c75463713",
    "field_id": "00000000-0000-0000-0000-000000000004",
    "name": "REF ipsum",
    "value": "ipsum",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "aliqua"
      },
      {
        "langu_id": "en",
        "value": "qui"
      },
      {
        "langu_id": "en",
        "value": "tempor"
      }
    ]
  },
  {
    "id": "3dfd5805-1af9-4ad6-9692-d50885d4fa13",
    "field_id": "00000000-0000-0000-0000-000000000005",
    "name": "ALT amet",
    "value": "amet",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "reprehenderit"
      },
      {
        "langu_id": "en",
        "value": "ullamco"
      },
      {
        "langu_id": "en",
        "value": "incididunt"
      }
    ]
  },
  {
    "id": "f4e93f62-2dc3-4791-9ab9-bba4db2971b7",
    "field_id": "00000000-0000-0000-0000-000000000006",
    "name": "QUAL aute",
    "value": "aute",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "do"
      },
      {
        "langu_id": "en",
        "value": "minim"
      },
      {
        "langu_id": "en",
        "value": "adipisicing"
      }
    ]
  },
  {
    "id": "9e833a97-421d-4763-bced-4ddbc61168ee",
    "field_id": "00000000-0000-0000-0000-000000000007",
    "name": "FILTER voluptate",
    "value": "voluptate",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "aliquip"
      },
      {
        "langu_id": "en",
        "value": "ea"
      },
      {
        "langu_id": "en",
        "value": "cillum"
      }
    ]
  },
  {
    "id": "7bbf9b1d-35bb-4d8b-8354-785b722562df",
    "field_id": "00000000-0000-0000-0000-000000000010",
    "name": "FAMILY_ID irure",
    "value": "irure",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "voluptate"
      },
      {
        "langu_id": "en",
        "value": "fugiat"
      },
      {
        "langu_id": "en",
        "value": "eiusmod"
      }
    ]
  },
  {
    "id": "19c4a88d-38c8-460e-9eb6-46d0ae2dd1e1",
    "field_id": "00000000-0000-0000-0000-000000000011",
    "name": "FAMILY_INFO eu",
    "value": "eu",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "ut"
      },
      {
        "langu_id": "en",
        "value": "incididunt"
      },
      {
        "langu_id": "en",
        "value": "ut"
      }
    ]
  },
  {
    "id": "f3c855bb-beed-4bd0-919d-3d64b8e89d6d",
    "field_id": "00000000-0000-0000-0000-000000000012",
    "name": "GENDER pariatur",
    "value": "pariatur",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "eiusmod"
      },
      {
        "langu_id": "en",
        "value": "laboris"
      },
      {
        "langu_id": "en",
        "value": "id"
      }
    ]
  },
  {
    "id": "c9d297fd-a580-4d0f-adcb-afd194c564d5",
    "field_id": "00000000-0000-0000-0000-000000000013",
    "name": "PHENOTYPE veniam",
    "value": "veniam",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "proident"
      },
      {
        "langu_id": "en",
        "value": "amet"
      },
      {
        "langu_id": "en",
        "value": "in"
      }
    ]
  },
  {
    "id": "d7ed64de-9004-4d1e-b752-930df9ee8d7f",
    "field_id": "00000000-0000-0000-0000-000000000014",
    "name": "SAMPLE_ID ea",
    "value": "ea",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "in"
      },
      {
        "langu_id": "en",
        "value": "non"
      },
      {
        "langu_id": "en",
        "value": "et"
      }
    ]
  },
  {
    "id": "a4d214d2-565c-459a-a146-619ef4b1cdb6",
    "field_id": "00000000-0000-0000-0000-000000000015",
    "name": "SAMPLE_TYPE nisi",
    "value": "nisi",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "sunt"
      },
      {
        "langu_id": "en",
        "value": "do"
      },
      {
        "langu_id": "en",
        "value": "excepteur"
      }
    ]
  },
  {
    "id": "a3690805-f813-4b33-8cfe-f5f8979c4b03",
    "field_id": "00000000-0000-0000-0000-000000000016",
    "name": "REFERENCE commodo",
    "value": "commodo",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "duis"
      },
      {
        "langu_id": "en",
        "value": "laborum"
      },
      {
        "langu_id": "en",
        "value": "irure"
      }
    ]
  },
  {
    "id": "605a6242-a5ec-4640-b261-243a20a7ce50",
    "field_id": "00000000-0000-0000-0000-000000000017",
    "name": "COMMENT do",
    "value": "do",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "commodo"
      },
      {
        "langu_id": "en",
        "value": "veniam"
      },
      {
        "langu_id": "en",
        "value": "aliqua"
      }
    ]
  },
  {
    "id": "91ddedce-5f0d-4f53-b11a-f41cffa0ebd7",
    "field_id": "a9ec5ab7-2ec9-46ce-a4c9-d0cb18da7115",
    "name": "INFO_NR sint",
    "value": "sint",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "in"
      },
      {
        "langu_id": "en",
        "value": "fugiat"
      },
      {
        "langu_id": "en",
        "value": "sint"
      }
    ]
  },
  {
    "id": "5b14b3fd-179b-4bb3-aa52-61b2fe1f0dc0",
    "field_id": "b5467aa6-e3f3-4906-93b5-7d80f38bc877",
    "name": "INFO_DP ea",
    "value": "ea",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "eu"
      },
      {
        "langu_id": "en",
        "value": "sint"
      },
      {
        "langu_id": "en",
        "value": "fugiat"
      }
    ]
  },
  {
    "id": "d71a4bc2-f85d-4c66-821d-44d373447fbd",
    "field_id": "f2e9f391-fe09-4303-ac51-c53100845d9b",
    "name": "INFO_RO cupidatat",
    "value": "cupidatat",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "officia"
      },
      {
        "langu_id": "en",
        "value": "irure"
      },
      {
        "langu_id": "en",
        "value": "officia"
      }
    ]
  },
  {
    "id": "e89f1603-5b52-4487-9c12-e8eea7063cfd",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM quis",
    "value": "quis",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "est"
      },
      {
        "langu_id": "en",
        "value": "dolor"
      },
      {
        "langu_id": "en",
        "value": "exercitation"
      }
    ]
  },
  {
    "id": "31e3d207-8195-4f9f-8ef5-151d8a2339b2",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM eu",
    "value": "eu",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "aute"
      },
      {
        "langu_id": "en",
        "value": "tempor"
      },
      {
        "langu_id": "en",
        "value": "magna"
      }
    ]
  },
  {
    "id": "a3652fd9-2353-43ec-bdc3-6675be4bd188",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM est",
    "value": "est",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "nostrud"
      },
      {
        "langu_id": "en",
        "value": "excepteur"
      },
      {
        "langu_id": "en",
        "value": "commodo"
      }
    ]
  },
  {
    "id": "5442c583-8cf9-4d5c-a092-845eba48a527",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM estu",
    "value": "estu",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "sit"
      },
      {
        "langu_id": "en",
        "value": "enim"
      },
      {
        "langu_id": "en",
        "value": "aliquip"
      }
    ]
  },
  {
    "id": "682823de-3e81-4083-836c-83d2e917876a",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM irure",
    "value": "irure",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "qui"
      },
      {
        "langu_id": "en",
        "value": "culpa"
      },
      {
        "langu_id": "en",
        "value": "cillum"
      }
    ]
  },
  {
    "id": "7fa4ef7f-9a3f-476a-b211-86187adbe2a4",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM dolore",
    "value": "dolore",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "laboris"
      },
      {
        "langu_id": "en",
        "value": "in"
      },
      {
        "langu_id": "en",
        "value": "deserunt"
      }
    ]
  },
  {
    "id": "c6414b9e-7cf0-4f30-844e-5fab97cd8cb3",
    "field_id": "00000000-0000-0000-0000-000000000001",
    "name": "CHROM elit",
    "value": "elit",
    "synonyms": [
      {
        "langu_id": "en",
        "value": "dolore"
      },
      {
        "langu_id": "en",
        "value": "proident"
      },
      {
        "langu_id": "en",
        "value": "sunt"
      }
    ]
  }
]
